### ISSUE TITLE
News Image not appearing in staging

### ISSUE THREAD

**Issue by andrejjh** [gbif/hp-gbif-be#25]
**Describe the bug**
News image not appearing although image present in the assets folder.

**To Reproduce**
1. Go to News
2. Click on Local News
3. See error : The Metabarcoding news appears but not the associated image (assets/images/photos/MDT.png)

**Expected behavior**
Image should appear in the list news and on top of news item.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Brave

**Additional context**
Staging context https://gbif-be.hp.gbif-staging.org/post/2024/metabarcoding/
Works correctly when served locally

**Comment by MortenHofft** [comment]
Thanks
Looks like the build process have changed something. As far as I can see the issue is that the build server is using the production domain in staging. 
And because that is a new post, then the image do not exist in production, so it fails. Whereas the other images are in prod. 
The reason it works locally is because those images aren't being processed by our image cache server, that only happens on deployed versions.

@MattBlissett you will know which variables are overwritten for which environment. Am I missing something in config? 

But it is a bit surprising, since this has worked in the past.
And still do for e.g. https://swissnatcoll.hp.gbif-staging.org/post/2024/call-to-contribute/ that was deployed around the same time as the gbif-be site.

**Comment by MortenHofft** [comment]
I do not see this bug on any other sites I've looked at. Only this. And it is using prod images in both uat and staging. 
I cannot see anything different in the config or use of images compared to other sites. I'm not sure what to do at this point, but I'm fairly certain it would work if you did a production release, but obviously that is a bit of a leap of faith.

It would still be a bug of course, but you could proceed with your news item

**Comment by MattBlissett** [comment]
I've fixed it.

I accidentally deleted the line adding the staging configuration override (_config_staging.yml) when working on adding the validation for config.js.

The Swiss portal works because the URL in _config.yml is the staging one, i.e. it hasn't yet been launched.
