### ISSUE TITLE
Dataset and publisher links work in english, but not in french

### ISSUE THREAD

**Issue by andrejjh** [gbif/hp-gbif-be#4]
The english version is fine, datasets and publishers list are fine and dataset/publisher detail also.

However in the french version datasets/publishers list appear but their links are incorrectly prefixed with '/fr/fr'
eg http://127.0.0.1:4000/fr/fr/dataset/2d59e5db-57ad-41ff-97d6-11f5fb264527

Therefore, it's not possible to view a particular dataset/publisher.

**Comment by andrejjh** [comment]
The problem only occurs when **exploring datasets/publishers in french**.
Collections, occurrences and literature search are fine.

**Comment by MortenHofft** [comment]
Canadensys also has a multilingual site. You might find it useful to look at their site

https://canadensys.hp.gbif-staging.org/fr/dataset/ec186b76-898c-435b-9aea-ebbd5785a25f
https://canadensys.hp.gbif-staging.org/dataset/ec186b76-898c-435b-9aea-ebbd5785a25f

I will look and see if I can find the cause

**Comment by MortenHofft** [comment]
I've changed the config to include collection search so it shows properly in the menu. Currently it links to grscicoll for details. To change that add `collectionKey` to the list of available routes.

The real problem was this line https://github.com/gbif/hp-gbif-be/commit/1136b0cd384a6a7c6ccc50c378586a132759be27#diff-e27d679151a5d301f02ee0f620edf1dcc7fcccf15e474ecec8af9b8022aa8fa6R18

Which shouldn't be required so this is a bug I should fix. But adding it will fix the issue. At the moment this is a requirement for multilingual sites.
